# Default values for mc-multiserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# See https://hub.docker.com/r/itzg/bungeecord for explanation of the variables below
proxy:
  type: "WATERFALL"
  motd: "Welcome to the Minecraft Server"
  enable_rcon: "true"
  rcon_password: "passw0rd!"
  max_players: 20

# See https://github.com/itzg/docker-minecraft-server/blob/master/README.md for explanation of the variables below
# This will create a stateful set with {count} identical minecraft servers
#  attached to the bungeecord proxy
servers:
  count: 3
  type: "PAPER"
  version: "1.16.5"
  difficulty: "normal"
  pvp: "false"
  ops: "admin"
  enable_rcon: "true"
  rcon_password: "passw0rd!"
  generate_structures: "true"
  mode: "creative"
  storageSize: "1Gi"
