kind: Service
apiVersion: v1
metadata:
  name: proxy
spec:
  type: LoadBalancer
  selector:
    app: proxy
  ports:
  - protocol: TCP
    port: 25565
    targetPort: 25577
  externalTrafficPolicy: Local
