apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      hostNetwork: false
      containers:
      - name: minecraft
        image: itzg/bungeecord
        envFrom:
          - configMapRef:
              name: proxy-config-env
        volumeMounts:
          - name: server
            mountPath: "/server"
          - name: config
            mountPath: "/config"
      volumes:
      - name: server
        emptyDir:
          {}
      - name: config
        configMap:
          name: proxy-config-files
