apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config-files
data:
  config.yml: |
    ip_forward: true
    online_mode: true
    servers:
      {{- range .Values.servers }}
      {{ .name }}:
        address: minecraft-{{ .name }}-service
        restricted: false
      {{- end }}
    listeners:
      - motd: {{ .Values.proxy.motd }}
        priorities:
        - {{ .Values.lobbyServer }}
        proxy_protocol: false
        max_players: {{ .Values.proxy.max_players }}
