{{- range .Values.servers }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
spec:
  selector:
    matchLabels:
      app: minecraft
      server: {{ .name }}
  template:
    metadata:
      labels:
        app: minecraft
        server: {{ .name }}
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        envFrom:
          - configMapRef:
              name: {{ .name }}-config-env
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
        - name: {{ .name }}-server-data
          mountPath: /data
        - name: {{ .name }}-config-files
          mountPath: /config
      volumes:
        - name: {{ .name }}-config-files
          configMap:
            name: server-config-files
        - name: {{ .name }}-server-data
          persistentVolumeClaim:
            claimName: {{ .name }}-pvc
---
{{ end }}