{{- range .Values.servers }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-pvc
spec:
  accessModes:
  - ReadWriteOnce
#  storageClassName: {{ .storageClassName }}
  resources:
    requests:
      storage: {{ .storageSize }}
---
{{ end }}